version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"  # Edge port
      - "4575:4575"  # SNS port (if needed)
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-east-1
      - INITIALIZE=true
    volumes:
      - "./init-sqs.sh:/etc/localstack/init/ready.d/init-sqs.sh"  # Script for SQS initialization
      - "/var/run/docker.sock:/var/run/docker.sock"

  redis:
    image: redis:6.0.9
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis-data:/data"